warning: Cannot check if git requires authentication.
apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: test-app-new-app
    name: test-app-new-app
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: test-app-new-app
    name: test-app-new-app
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: test-app-new-app:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: master
        uri: git@github.com:piyush-garg/test-app-new-app.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:10
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: l9W1VK2v-YWPhhc1LbZq
      type: GitHub
    - generic:
        secret: HhFYG6e4Dp6u0IZbb2cC
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: test-app-new-app
    name: test-app-new-app
  spec:
    replicas: 1
    selector:
      app: test-app-new-app
      deploymentconfig: test-app-new-app
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: test-app-new-app
          deploymentconfig: test-app-new-app
      spec:
        containers:
        - image: test-app-new-app:latest
          name: test-app-new-app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - test-app-new-app
        from:
          kind: ImageStreamTag
          name: test-app-new-app:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: test-app-new-app
    name: test-app-new-app
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: test-app-new-app
      deploymentconfig: test-app-new-app
  status:
    loadBalancer: {}
kind: List
metadata: {}
